name: Build

on: [pull_request, workflow_dispatch]

jobs:
  build-lint-test:
    name: Build, install and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v4
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # ratchet:actions/setup-node@v6.3.0
        with:
          node-version: '24'
          cache: npm
          registry-url: "https://npm.pkg.github.com"
      - name: Install dependencies
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
        run: npm ci
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Build server
        run: npm run build:server
