name: 'Remove old images'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2-5 * * *'

jobs:
  remove-images:
    name: 'Remove old images job'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # ratchet:actions/delete-package-versions@v5
        with:
          package-name: 'familie-ef-minside'
          package-type: 'container'
          min-versions-to-keep: 1
